spring.application.name=demo
server.port=8080
jwt.secret=3f8a2b1c9d4e7f6a5b0c2d8e1f3a7b4c9d2e5f8a1b4c7d0e3f6a9b2c5d8e1f4
jwt.expiration=86400000000
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter=DEBUG
spring.mvc.log-request-details=true
logging.level.org.springframework.security=DEBUG


spring.datasource.url=jdbc:postgresql://localhost:5433/postgres?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
#logging.level.org.springframework.jdbc.core=DEBUG
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#AVNS_dUm-L24rB7DojFHqgjj
spring.security.oauth2.client.registration.google.client-id=1017825382510-qfpoj604g9tdcsjr8vmvqno5k2fjnlvi.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.google.redirect-uri=https://c8fd-123-201-171-91.ngrok-free.app/login/oauth/google

spring.security.oauth2.client.registration.google.client-name=Google